<BudgetTracker>:
    orientation: 'vertical'
    AnchorLayout:
        anchor_y: "top"
        size_hint: 1, None
        height: self.children[0].height - 25  # Dynamically adjust to AppBar's height
        AppBar:
        NavBar:
    ContentArea:
        id: content_area

<ContentArea>:
    DashboardScreen:
    TransactionScreen:

<DashboardScreen>:
    DashboardView:

<TransactionScreen>:
    TransactionView: